backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: "trek"
    label: "Trek"
    folder: "content/trek"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Description", name: "seodescription", widget: "text", required: false}
      - {label: Image, name: "imagepath", widget: "image", required: false}
      - {label: "Image Description", name: "imgdesc", widget: "text", required: false}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "expedition"
    label: "Expedition"
    folder: "content/expedition"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Description", name: "seodescription", widget: "text", required: false}
      - {label: Image, name: "imagepath", widget: "image", required: false}
      - {label: "Image Description", name: "imgdesc", widget: "text", required: false}
      - {label: "Body", name: "body", widget: "markdown"}
